"""Public schema surface: `TrackDocument` tree + the five pipeline IR cores."""

from trackgen.schema.document import (
    Bus,
    Channel,
    DocumentModel,
    EffectPatch,
    EffectType,
    Header,
    InstrumentPatch,
    InstrumentType,
    Master,
    Meta,
    NoteEvent,
    PolySynthVoice,
    Role,
    Section,
    Send,
    Tempo,
    TimeSignature,
    Track,
    TrackDocument,
)
from trackgen.schema.ir import (
    ArrangementEntry,
    ArrangementPlan,
    ChordEvent,
    ChordQuality,
    ChordSpec,
    FormSection,
    GenerationPlan,
    HarmonicPlan,
    IRModel,
    Key,
    Phrase,
    PhraseNote,
    Register,
    SeedSpec,
    SongForm,
    StylePackRef,
    SwingSpec,
)
from trackgen.schema.ir import TimeSignature as PlanTimeSignature

__all__ = [
    # document.py
    "Bus",
    "Channel",
    "DocumentModel",
    "EffectPatch",
    "EffectType",
    "Header",
    "InstrumentPatch",
    "InstrumentType",
    "Master",
    "Meta",
    "NoteEvent",
    "PolySynthVoice",
    "Role",
    "Section",
    "Send",
    "Tempo",
    "TimeSignature",
    "Track",
    "TrackDocument",
    # ir.py
    "ArrangementEntry",
    "ArrangementPlan",
    "ChordEvent",
    "ChordQuality",
    "ChordSpec",
    "FormSection",
    "GenerationPlan",
    "HarmonicPlan",
    "IRModel",
    "Key",
    "Phrase",
    "PhraseNote",
    "PlanTimeSignature",
    "Register",
    "SeedSpec",
    "SongForm",
    "StylePackRef",
    "SwingSpec",
]
